//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.6
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace ImagePackageGenerator.swig {

unsafe partial class Document : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  private bool swigCMemOwnBase;

  internal Document(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwnBase = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Document obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~Document() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwnBase) {
          swigCMemOwnBase = false;
          PSDParserPINVOKE.delete_Document(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public Document() : this(PSDParserPINVOKE.new_Document(), true) {
  }

  public static Document Create(System.IntPtr data, int size) {
    global::System.IntPtr cPtr = PSDParserPINVOKE.Document_Create(data, size);
    Document ret = (cPtr == global::System.IntPtr.Zero) ? null : new Document(cPtr, true);
    return ret;
  }

  public int GetLayerCount() {
    int ret = PSDParserPINVOKE.Document_GetLayerCount(swigCPtr);
    if (PSDParserPINVOKE.SWIGPendingException.Pending) throw PSDParserPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public Layer GetLayer(int index) {
    global::System.IntPtr cPtr = PSDParserPINVOKE.Document_GetLayer(swigCPtr, index);
    Layer ret = (cPtr == global::System.IntPtr.Zero) ? null : new Layer(cPtr, true);
    if (PSDParserPINVOKE.SWIGPendingException.Pending) throw PSDParserPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public int GetWidth() {
    int ret = PSDParserPINVOKE.Document_GetWidth(swigCPtr);
    if (PSDParserPINVOKE.SWIGPendingException.Pending) throw PSDParserPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public uint GetDepth() {
    uint ret = PSDParserPINVOKE.Document_GetDepth(swigCPtr);
    if (PSDParserPINVOKE.SWIGPendingException.Pending) throw PSDParserPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}

}
