//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.6
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace ImagePackageGenerator.swig {

unsafe partial class Layer : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  private bool swigCMemOwnBase;

  internal Layer(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwnBase = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Layer obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~Layer() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwnBase) {
          swigCMemOwnBase = false;
          PSDParserPINVOKE.delete_Layer(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public Layer() : this(PSDParserPINVOKE.new_Layer(), true) {
  }

  public void Extend(Rect newArea) {
    PSDParserPINVOKE.Layer_Extend(swigCPtr, Rect.getCPtr(newArea));
    if (PSDParserPINVOKE.SWIGPendingException.Pending) throw PSDParserPINVOKE.SWIGPendingException.Retrieve();
  }

  public System.IntPtr GetData() { return PSDParserPINVOKE.Layer_GetData(swigCPtr); }

  public Rect GetRect() {
    Rect ret = new Rect(PSDParserPINVOKE.Layer_GetRect(swigCPtr), true);
    if (PSDParserPINVOKE.SWIGPendingException.Pending) throw PSDParserPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public string GetName() {
    string ret = System.Runtime.InteropServices.Marshal.PtrToStringUni(PSDParserPINVOKE.Layer_GetName(swigCPtr));
    if (PSDParserPINVOKE.SWIGPendingException.Pending) throw PSDParserPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public LayerObjectType ObjectType {
    set {
      PSDParserPINVOKE.Layer_ObjectType_set(swigCPtr, (int)value);
      if (PSDParserPINVOKE.SWIGPendingException.Pending) throw PSDParserPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      LayerObjectType ret = (LayerObjectType)PSDParserPINVOKE.Layer_ObjectType_get(swigCPtr);
      if (PSDParserPINVOKE.SWIGPendingException.Pending) throw PSDParserPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public LayerAdditionalObjectType AdditionalObjectType {
    set {
      PSDParserPINVOKE.Layer_AdditionalObjectType_set(swigCPtr, (int)value);
      if (PSDParserPINVOKE.SWIGPendingException.Pending) throw PSDParserPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      LayerAdditionalObjectType ret = (LayerAdditionalObjectType)PSDParserPINVOKE.Layer_AdditionalObjectType_get(swigCPtr);
      if (PSDParserPINVOKE.SWIGPendingException.Pending) throw PSDParserPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

}

}
