using System;
namespace asd {
	/// <summary>
	/// 回転行列の計算順序 
	///	</summary>
	public enum RotationOrder : int
	{
		/// <summary>
		/// 
		/// </summary>
		QUATERNION = asd.swig.RotationOrder.QUATERNION,
		/// <summary>
		/// 
		/// </summary>
		XZY = asd.swig.RotationOrder.XZY,
		/// <summary>
		/// 
		/// </summary>
		XYZ = asd.swig.RotationOrder.XYZ,
		/// <summary>
		/// 
		/// </summary>
		ZXY = asd.swig.RotationOrder.ZXY,
		/// <summary>
		/// 
		/// </summary>
		ZYX = asd.swig.RotationOrder.ZYX,
		/// <summary>
		/// 
		/// </summary>
		YXZ = asd.swig.RotationOrder.YXZ,
		/// <summary>
		/// 
		/// </summary>
		YZX = asd.swig.RotationOrder.YZX,
		/// <summary>
		/// 
		/// </summary>
		AXIS = asd.swig.RotationOrder.AXIS,
	}

	/// <summary>
	/// キー間の補間方法 
	///	</summary>
	public enum InterpolationType : int
	{
		/// <summary>
		/// 次のキーまで定数で補間 
		/// </summary>
		Constant = asd.swig.InterpolationType.Constant,
		/// <summary>
		/// 次のキーまで線形で補間 
		/// </summary>
		Linear = asd.swig.InterpolationType.Linear,
		/// <summary>
		/// 次のキーまで三次方程式で補間 
		/// </summary>
		Cubic = asd.swig.InterpolationType.Cubic,
	}

	/// <summary>
	/// 起動時に自動的に生成されるレイヤーの種類 
	///	</summary>
	public enum AutoGeneratedLayerType : int
	{
		/// <summary>
		/// 
		/// </summary>
		Layer2D = asd.swig.AutoGeneratedLayerType.Layer2D,
		/// <summary>
		/// 
		/// </summary>
		Layer3D = asd.swig.AutoGeneratedLayerType.Layer3D,
		/// <summary>
		/// 
		/// </summary>
		None = asd.swig.AutoGeneratedLayerType.Nothing,
	}

	/// <summary>
	/// レイヤーの種類 
	///	</summary>
	public enum LayerType : int
	{
		/// <summary>
		/// 
		/// </summary>
		Layer2D = asd.swig.LayerType.Layer2D,
		/// <summary>
		/// 
		/// </summary>
		Layer3D = asd.swig.LayerType.Layer3D,
	}

	/// <summary>
	/// 
	///	</summary>
	public enum WritingDirection : int
	{
		/// <summary>
		/// 
		/// </summary>
		Vertical = asd.swig.WritingDirection.Vertical,
		/// <summary>
		/// 
		/// </summary>
		Horizontal = asd.swig.WritingDirection.Horizontal,
	}

	/// <summary>
	/// フレームレートの制御方法 
	///	</summary>
	public enum FramerateMode : int
	{
		/// <summary>
		/// 固定フレームレート 
		/// </summary>
		Constant = asd.swig.FramerateMode.Constant,
		/// <summary>
		/// 可変フレームレート 
		/// </summary>
		Variable = asd.swig.FramerateMode.Variable,
	}

	/// <summary>
	/// 
	///	</summary>
	public enum TextureFormat : int
	{
		/// <summary>
		/// 
		/// </summary>
		R8G8B8A8_UNORM = asd.swig.TextureFormat.R8G8B8A8_UNORM,
		/// <summary>
		/// 
		/// </summary>
		R32G32B32A32_FLOAT = asd.swig.TextureFormat.R32G32B32A32_FLOAT,
		/// <summary>
		/// 
		/// </summary>
		R8G8B8A8_UNORM_SRGB = asd.swig.TextureFormat.R8G8B8A8_UNORM_SRGB,
		/// <summary>
		/// 
		/// </summary>
		R16G16_FLOAT = asd.swig.TextureFormat.R16G16_FLOAT,
		/// <summary>
		/// 
		/// </summary>
		R8_UNORM = asd.swig.TextureFormat.R8_UNORM,
		/// <summary>
		/// 
		/// </summary>
		BC1 = asd.swig.TextureFormat.BC1,
		/// <summary>
		/// 
		/// </summary>
		BC2 = asd.swig.TextureFormat.BC2,
		/// <summary>
		/// 
		/// </summary>
		BC3 = asd.swig.TextureFormat.BC3,
		/// <summary>
		/// 
		/// </summary>
		BC1_SRGB = asd.swig.TextureFormat.BC1_SRGB,
		/// <summary>
		/// 
		/// </summary>
		BC2_SRGB = asd.swig.TextureFormat.BC2_SRGB,
		/// <summary>
		/// 
		/// </summary>
		BC3_SRGB = asd.swig.TextureFormat.BC3_SRGB,
	}

	/// <summary>
	/// 
	///	</summary>
	public enum TextureClassType : int
	{
		/// <summary>
		/// 
		/// </summary>
		Texture2D = asd.swig.TextureClassType.Texture2D,
		/// <summary>
		/// 
		/// </summary>
		RenderTexture2D = asd.swig.TextureClassType.RenderTexture2D,
		/// <summary>
		/// 
		/// </summary>
		CubemapTexture = asd.swig.TextureClassType.CubemapTexture,
		/// <summary>
		/// 
		/// </summary>
		DepthBuffer = asd.swig.TextureClassType.DepthBuffer,
	}

	/// <summary>
	/// 描画時のブレンドモードを表す列挙体 
	///	</summary>
	public enum AlphaBlendMode : int
	{
		/// <summary>
		/// 不透明 
		/// </summary>
		Opacity = asd.swig.AlphaBlendMode.Opacity,
		/// <summary>
		/// 透明 
		/// </summary>
		Blend = asd.swig.AlphaBlendMode.Blend,
		/// <summary>
		/// 加算 
		/// </summary>
		Add = asd.swig.AlphaBlendMode.Add,
		/// <summary>
		/// 減算 
		/// </summary>
		Sub = asd.swig.AlphaBlendMode.Sub,
		/// <summary>
		/// 乗算 
		/// </summary>
		Mul = asd.swig.AlphaBlendMode.Mul,
		/// <summary>
		/// 全加算(内部処理用) 
		/// </summary>
		AddAll = asd.swig.AlphaBlendMode.AddAll,
	}

	/// <summary>
	/// 
	///	</summary>
	public enum TextureFilterType : int
	{
		/// <summary>
		/// 
		/// </summary>
		Nearest = asd.swig.TextureFilterType.Nearest,
		/// <summary>
		/// 
		/// </summary>
		Linear = asd.swig.TextureFilterType.Linear,
	}

	/// <summary>
	/// 
	///	</summary>
	public enum TextureWrapType : int
	{
		/// <summary>
		/// 
		/// </summary>
		Repeat = asd.swig.TextureWrapType.Repeat,
		/// <summary>
		/// 
		/// </summary>
		Clamp = asd.swig.TextureWrapType.Clamp,
	}

	/// <summary>
	/// 
	///	</summary>
	public enum CullingType : int
	{
		/// <summary>
		/// 
		/// </summary>
		Front = asd.swig.CullingType.Front,
		/// <summary>
		/// 
		/// </summary>
		Back = asd.swig.CullingType.Back,
		/// <summary>
		/// 
		/// </summary>
		Double = asd.swig.CullingType.Double,
	}

	/// <summary>
	/// 描画方法 
	///	</summary>
	public enum GraphicsDeviceType : int
	{
		/// <summary>
		/// 実行環境で最も安定している描画方法(初期化時に使用) 
		/// </summary>
		Default = asd.swig.GraphicsDeviceType.Default,
		/// <summary>
		/// DirectX11. 
		/// </summary>
		DirectX11 = asd.swig.GraphicsDeviceType.DirectX11,
		/// <summary>
		/// OpenGL. 
		/// </summary>
		OpenGL = asd.swig.GraphicsDeviceType.OpenGL,
	}

	/// <summary>
	/// 
	///	</summary>
	public enum Object2DType : int
	{
		/// <summary>
		/// 
		/// </summary>
		Unknown = asd.swig.Object2DType.Unknown,
		/// <summary>
		/// 
		/// </summary>
		Texture = asd.swig.Object2DType.Texture,
		/// <summary>
		/// 
		/// </summary>
		Camera = asd.swig.Object2DType.Camera,
		/// <summary>
		/// 
		/// </summary>
		Effect = asd.swig.Object2DType.Effect,
		/// <summary>
		/// 
		/// </summary>
		Text = asd.swig.Object2DType.Text,
		/// <summary>
		/// 
		/// </summary>
		Map = asd.swig.Object2DType.Map,
		/// <summary>
		/// 
		/// </summary>
		Geometry = asd.swig.Object2DType.Geometry,
	}

	/// <summary>
	/// 
	///	</summary>
	public enum RenderedObject3DType : int
	{
		/// <summary>
		/// 
		/// </summary>
		Unknown = asd.swig.RenderedObject3DType.Unknown,
		/// <summary>
		/// 
		/// </summary>
		Mesh = asd.swig.RenderedObject3DType.Mesh,
		/// <summary>
		/// 
		/// </summary>
		Camera = asd.swig.RenderedObject3DType.Camera,
		/// <summary>
		/// 
		/// </summary>
		Effect = asd.swig.RenderedObject3DType.Effect,
		/// <summary>
		/// 
		/// </summary>
		DirectionalLight = asd.swig.RenderedObject3DType.DirectionalLight,
		/// <summary>
		/// 
		/// </summary>
		MassObject = asd.swig.RenderedObject3DType.MassObject,
		/// <summary>
		/// 
		/// </summary>
		Terrain = asd.swig.RenderedObject3DType.Terrain,
	}

	/// <summary>
	/// シェーダーに対して外部から設定可能なプロパティの変数の種類 
	///	</summary>
	public enum ShaderVariableType : int
	{
		/// <summary>
		/// 
		/// </summary>
		Unknown = asd.swig.ShaderVariableType.Unknown,
		/// <summary>
		/// 
		/// </summary>
		Float = asd.swig.ShaderVariableType.Float,
		/// <summary>
		/// 
		/// </summary>
		Vector2DF = asd.swig.ShaderVariableType.Vector2DF,
		/// <summary>
		/// 
		/// </summary>
		Vector3DF = asd.swig.ShaderVariableType.Vector3DF,
		/// <summary>
		/// 
		/// </summary>
		Vector4DF = asd.swig.ShaderVariableType.Vector4DF,
		/// <summary>
		/// 
		/// </summary>
		Vector4DF_Array = asd.swig.ShaderVariableType.Vector4DF_Array,
		/// <summary>
		/// 
		/// </summary>
		Matrix44 = asd.swig.ShaderVariableType.Matrix44,
		/// <summary>
		/// 
		/// </summary>
		Matrix44_Array = asd.swig.ShaderVariableType.Matrix44_Array,
		/// <summary>
		/// 
		/// </summary>
		Texture2D = asd.swig.ShaderVariableType.Texture2D,
		/// <summary>
		/// 
		/// </summary>
		CubemapTexture = asd.swig.ShaderVariableType.CubemapTexture,
	}

	/// <summary>
	/// 3D描画時に表示されるバッファ 
	///	</summary>
	public enum VisualizedBufferType : int
	{
		/// <summary>
		/// 
		/// </summary>
		FinalImage = asd.swig.VisualizedBufferType.FinalImage,
		/// <summary>
		/// 
		/// </summary>
		DiffuseColor = asd.swig.VisualizedBufferType.DiffuseColor,
		/// <summary>
		/// 
		/// </summary>
		SpecularColor = asd.swig.VisualizedBufferType.SpecularColor,
		/// <summary>
		/// 
		/// </summary>
		Normal = asd.swig.VisualizedBufferType.Normal,
		/// <summary>
		/// 
		/// </summary>
		Smoothness = asd.swig.VisualizedBufferType.Smoothness,
		/// <summary>
		/// 
		/// </summary>
		Environment = asd.swig.VisualizedBufferType.Environment,
		/// <summary>
		/// 
		/// </summary>
		Occlusion = asd.swig.VisualizedBufferType.Occlusion,
	}

	/// <summary>
	/// マウスボタンの押し状態を示す列挙型 
	///	</summary>
	public enum MouseButtonState : int
	{
		/// <summary>
		/// ボタンをこのフレームで押した状態 
		/// </summary>
		Push = asd.swig.MouseButtonState.Push,
		/// <summary>
		/// ボタンをこのフレームで離した状態 
		/// </summary>
		Release = asd.swig.MouseButtonState.Release,
		/// <summary>
		/// ボタンを離し続けている状態 
		/// </summary>
		Free = asd.swig.MouseButtonState.Free,
		/// <summary>
		/// ボタンを押し続けている状態 
		/// </summary>
		Hold = asd.swig.MouseButtonState.Hold,
	}

	/// <summary>
	/// ACEで扱うキーボードのキー一覧 
	///	</summary>
	public enum Keys : int
	{
		/// <summary>
		/// 
		/// </summary>
		Unknown = asd.swig.Keys.Unknown,
		/// <summary>
		/// 
		/// </summary>
		Space = asd.swig.Keys.Space,
		/// <summary>
		/// 
		/// </summary>
		Apostrophe = asd.swig.Keys.Apostrophe,
		/// <summary>
		/// 
		/// </summary>
		Comma = asd.swig.Keys.Comma,
		/// <summary>
		/// 
		/// </summary>
		Minus = asd.swig.Keys.Minus,
		/// <summary>
		/// 
		/// </summary>
		Period = asd.swig.Keys.Period,
		/// <summary>
		/// 
		/// </summary>
		Slash = asd.swig.Keys.Slash,
		/// <summary>
		/// 
		/// </summary>
		Num0 = asd.swig.Keys.Num0,
		/// <summary>
		/// 
		/// </summary>
		Num1 = asd.swig.Keys.Num1,
		/// <summary>
		/// 
		/// </summary>
		Num2 = asd.swig.Keys.Num2,
		/// <summary>
		/// 
		/// </summary>
		Num3 = asd.swig.Keys.Num3,
		/// <summary>
		/// 
		/// </summary>
		Num4 = asd.swig.Keys.Num4,
		/// <summary>
		/// 
		/// </summary>
		Num5 = asd.swig.Keys.Num5,
		/// <summary>
		/// 
		/// </summary>
		Num6 = asd.swig.Keys.Num6,
		/// <summary>
		/// 
		/// </summary>
		Num7 = asd.swig.Keys.Num7,
		/// <summary>
		/// 
		/// </summary>
		Num8 = asd.swig.Keys.Num8,
		/// <summary>
		/// 
		/// </summary>
		Num9 = asd.swig.Keys.Num9,
		/// <summary>
		/// 
		/// </summary>
		Semicolon = asd.swig.Keys.Semicolon,
		/// <summary>
		/// 
		/// </summary>
		Equal = asd.swig.Keys.Equal,
		/// <summary>
		/// 
		/// </summary>
		A = asd.swig.Keys.A,
		/// <summary>
		/// 
		/// </summary>
		B = asd.swig.Keys.B,
		/// <summary>
		/// 
		/// </summary>
		C = asd.swig.Keys.C,
		/// <summary>
		/// 
		/// </summary>
		D = asd.swig.Keys.D,
		/// <summary>
		/// 
		/// </summary>
		E = asd.swig.Keys.E,
		/// <summary>
		/// 
		/// </summary>
		F = asd.swig.Keys.F,
		/// <summary>
		/// 
		/// </summary>
		G = asd.swig.Keys.G,
		/// <summary>
		/// 
		/// </summary>
		H = asd.swig.Keys.H,
		/// <summary>
		/// 
		/// </summary>
		I = asd.swig.Keys.I,
		/// <summary>
		/// 
		/// </summary>
		J = asd.swig.Keys.J,
		/// <summary>
		/// 
		/// </summary>
		K = asd.swig.Keys.K,
		/// <summary>
		/// 
		/// </summary>
		L = asd.swig.Keys.L,
		/// <summary>
		/// 
		/// </summary>
		M = asd.swig.Keys.M,
		/// <summary>
		/// 
		/// </summary>
		N = asd.swig.Keys.N,
		/// <summary>
		/// 
		/// </summary>
		O = asd.swig.Keys.O,
		/// <summary>
		/// 
		/// </summary>
		P = asd.swig.Keys.P,
		/// <summary>
		/// 
		/// </summary>
		Q = asd.swig.Keys.Q,
		/// <summary>
		/// 
		/// </summary>
		R = asd.swig.Keys.R,
		/// <summary>
		/// 
		/// </summary>
		S = asd.swig.Keys.S,
		/// <summary>
		/// 
		/// </summary>
		T = asd.swig.Keys.T,
		/// <summary>
		/// 
		/// </summary>
		U = asd.swig.Keys.U,
		/// <summary>
		/// 
		/// </summary>
		V = asd.swig.Keys.V,
		/// <summary>
		/// 
		/// </summary>
		W = asd.swig.Keys.W,
		/// <summary>
		/// 
		/// </summary>
		X = asd.swig.Keys.X,
		/// <summary>
		/// 
		/// </summary>
		Y = asd.swig.Keys.Y,
		/// <summary>
		/// 
		/// </summary>
		Z = asd.swig.Keys.Z,
		/// <summary>
		/// 
		/// </summary>
		LeftBracket = asd.swig.Keys.LeftBracket,
		/// <summary>
		/// 
		/// </summary>
		Backslash = asd.swig.Keys.Backslash,
		/// <summary>
		/// 
		/// </summary>
		RightBracket = asd.swig.Keys.RightBracket,
		/// <summary>
		/// 
		/// </summary>
		GraveAccent = asd.swig.Keys.GraveAccent,
		/// <summary>
		/// 
		/// </summary>
		World1 = asd.swig.Keys.World1,
		/// <summary>
		/// 
		/// </summary>
		World2 = asd.swig.Keys.World2,
		/// <summary>
		/// 
		/// </summary>
		Escape = asd.swig.Keys.Escape,
		/// <summary>
		/// 
		/// </summary>
		Enter = asd.swig.Keys.Enter,
		/// <summary>
		/// 
		/// </summary>
		Tab = asd.swig.Keys.Tab,
		/// <summary>
		/// 
		/// </summary>
		Backspace = asd.swig.Keys.Backspace,
		/// <summary>
		/// 
		/// </summary>
		Insert = asd.swig.Keys.Insert,
		/// <summary>
		/// 
		/// </summary>
		Delete = asd.swig.Keys.Delete,
		/// <summary>
		/// 
		/// </summary>
		Right = asd.swig.Keys.Right,
		/// <summary>
		/// 
		/// </summary>
		Left = asd.swig.Keys.Left,
		/// <summary>
		/// 
		/// </summary>
		Down = asd.swig.Keys.Down,
		/// <summary>
		/// 
		/// </summary>
		Up = asd.swig.Keys.Up,
		/// <summary>
		/// 
		/// </summary>
		PageUp = asd.swig.Keys.PageUp,
		/// <summary>
		/// 
		/// </summary>
		PageDown = asd.swig.Keys.PageDown,
		/// <summary>
		/// 
		/// </summary>
		Home = asd.swig.Keys.Home,
		/// <summary>
		/// 
		/// </summary>
		End = asd.swig.Keys.End,
		/// <summary>
		/// 
		/// </summary>
		CapsLock = asd.swig.Keys.CapsLock,
		/// <summary>
		/// 
		/// </summary>
		ScrollLock = asd.swig.Keys.ScrollLock,
		/// <summary>
		/// 
		/// </summary>
		NumLock = asd.swig.Keys.NumLock,
		/// <summary>
		/// 
		/// </summary>
		PrintScreen = asd.swig.Keys.PrintScreen,
		/// <summary>
		/// 
		/// </summary>
		Pause = asd.swig.Keys.Pause,
		/// <summary>
		/// 
		/// </summary>
		F1 = asd.swig.Keys.F1,
		/// <summary>
		/// 
		/// </summary>
		F2 = asd.swig.Keys.F2,
		/// <summary>
		/// 
		/// </summary>
		F3 = asd.swig.Keys.F3,
		/// <summary>
		/// 
		/// </summary>
		F4 = asd.swig.Keys.F4,
		/// <summary>
		/// 
		/// </summary>
		F5 = asd.swig.Keys.F5,
		/// <summary>
		/// 
		/// </summary>
		F6 = asd.swig.Keys.F6,
		/// <summary>
		/// 
		/// </summary>
		F7 = asd.swig.Keys.F7,
		/// <summary>
		/// 
		/// </summary>
		F8 = asd.swig.Keys.F8,
		/// <summary>
		/// 
		/// </summary>
		F9 = asd.swig.Keys.F9,
		/// <summary>
		/// 
		/// </summary>
		F10 = asd.swig.Keys.F10,
		/// <summary>
		/// 
		/// </summary>
		F11 = asd.swig.Keys.F11,
		/// <summary>
		/// 
		/// </summary>
		F12 = asd.swig.Keys.F12,
		/// <summary>
		/// 
		/// </summary>
		F13 = asd.swig.Keys.F13,
		/// <summary>
		/// 
		/// </summary>
		F14 = asd.swig.Keys.F14,
		/// <summary>
		/// 
		/// </summary>
		F15 = asd.swig.Keys.F15,
		/// <summary>
		/// 
		/// </summary>
		F16 = asd.swig.Keys.F16,
		/// <summary>
		/// 
		/// </summary>
		F17 = asd.swig.Keys.F17,
		/// <summary>
		/// 
		/// </summary>
		F18 = asd.swig.Keys.F18,
		/// <summary>
		/// 
		/// </summary>
		F19 = asd.swig.Keys.F19,
		/// <summary>
		/// 
		/// </summary>
		F20 = asd.swig.Keys.F20,
		/// <summary>
		/// 
		/// </summary>
		F21 = asd.swig.Keys.F21,
		/// <summary>
		/// 
		/// </summary>
		F22 = asd.swig.Keys.F22,
		/// <summary>
		/// 
		/// </summary>
		F23 = asd.swig.Keys.F23,
		/// <summary>
		/// 
		/// </summary>
		F24 = asd.swig.Keys.F24,
		/// <summary>
		/// 
		/// </summary>
		F25 = asd.swig.Keys.F25,
		/// <summary>
		/// 
		/// </summary>
		Keypad0 = asd.swig.Keys.Keypad0,
		/// <summary>
		/// 
		/// </summary>
		Keypad1 = asd.swig.Keys.Keypad1,
		/// <summary>
		/// 
		/// </summary>
		Keypad2 = asd.swig.Keys.Keypad2,
		/// <summary>
		/// 
		/// </summary>
		Keypad3 = asd.swig.Keys.Keypad3,
		/// <summary>
		/// 
		/// </summary>
		Keypad4 = asd.swig.Keys.Keypad4,
		/// <summary>
		/// 
		/// </summary>
		Keypad5 = asd.swig.Keys.Keypad5,
		/// <summary>
		/// 
		/// </summary>
		Keypad6 = asd.swig.Keys.Keypad6,
		/// <summary>
		/// 
		/// </summary>
		Keypad7 = asd.swig.Keys.Keypad7,
		/// <summary>
		/// 
		/// </summary>
		Keypad8 = asd.swig.Keys.Keypad8,
		/// <summary>
		/// 
		/// </summary>
		Keypad9 = asd.swig.Keys.Keypad9,
		/// <summary>
		/// 
		/// </summary>
		KeypadDecimal = asd.swig.Keys.KeypadDecimal,
		/// <summary>
		/// 
		/// </summary>
		KeypadDivide = asd.swig.Keys.KeypadDivide,
		/// <summary>
		/// 
		/// </summary>
		KeypadMultiply = asd.swig.Keys.KeypadMultiply,
		/// <summary>
		/// 
		/// </summary>
		KeypadSubstract = asd.swig.Keys.KeypadSubstract,
		/// <summary>
		/// 
		/// </summary>
		KeypadAdd = asd.swig.Keys.KeypadAdd,
		/// <summary>
		/// 
		/// </summary>
		KeypadEnter = asd.swig.Keys.KeypadEnter,
		/// <summary>
		/// 
		/// </summary>
		KeypadEqual = asd.swig.Keys.KeypadEqual,
		/// <summary>
		/// 
		/// </summary>
		LeftShift = asd.swig.Keys.LeftShift,
		/// <summary>
		/// 
		/// </summary>
		LeftControl = asd.swig.Keys.LeftControl,
		/// <summary>
		/// 
		/// </summary>
		LeftAlt = asd.swig.Keys.LeftAlt,
		/// <summary>
		/// 
		/// </summary>
		LeftWin = asd.swig.Keys.LeftWin,
		/// <summary>
		/// 
		/// </summary>
		RightShift = asd.swig.Keys.RightShift,
		/// <summary>
		/// 
		/// </summary>
		RightControl = asd.swig.Keys.RightControl,
		/// <summary>
		/// 
		/// </summary>
		RightAlt = asd.swig.Keys.RightAlt,
		/// <summary>
		/// 
		/// </summary>
		RightWin = asd.swig.Keys.RightWin,
		/// <summary>
		/// 
		/// </summary>
		Menu = asd.swig.Keys.Menu,
		/// <summary>
		/// 
		/// </summary>
		Last = asd.swig.Keys.Last,
		/// <summary>
		/// 
		/// </summary>
		MAX = asd.swig.Keys.MAX,
	}

	/// <summary>
	/// キーボードの押下状態を示す列挙型 
	///	</summary>
	public enum KeyState : int
	{
		/// <summary>
		/// キーをこのフレームで押した状態 
		/// </summary>
		Push = asd.swig.KeyState.Push,
		/// <summary>
		/// キーをこのフレームで離した状態 
		/// </summary>
		Release = asd.swig.KeyState.Release,
		/// <summary>
		/// キーを押し続けている状態 
		/// </summary>
		Hold = asd.swig.KeyState.Hold,
		/// <summary>
		/// キーを離し続けている状態 
		/// </summary>
		Free = asd.swig.KeyState.Free,
	}

	/// <summary>
	/// ジョイスティックのボタンの押し状態を示す列挙型 
	///	</summary>
	public enum JoystickButtonState : int
	{
		/// <summary>
		/// ボタンをこのフレームで押した状態 
		/// </summary>
		Push = asd.swig.JoystickButtonState.Push,
		/// <summary>
		/// ボタンをこのフレームで離した状態 
		/// </summary>
		Release = asd.swig.JoystickButtonState.Release,
		/// <summary>
		/// ボタンを離し続けている状態 
		/// </summary>
		Free = asd.swig.JoystickButtonState.Free,
		/// <summary>
		/// ボタンを押し続けている状態 
		/// </summary>
		Hold = asd.swig.JoystickButtonState.Hold,
	}

	/// <summary>
	/// 
	///	</summary>
	public enum LogLevel : int
	{
		/// <summary>
		/// 
		/// </summary>
		Error = asd.swig.LogLevel.Error,
		/// <summary>
		/// 
		/// </summary>
		Critical = asd.swig.LogLevel.Critical,
		/// <summary>
		/// 
		/// </summary>
		Warning = asd.swig.LogLevel.Warning,
		/// <summary>
		/// 
		/// </summary>
		Information = asd.swig.LogLevel.Information,
		/// <summary>
		/// 
		/// </summary>
		All = asd.swig.LogLevel.All,
	}

	/// <summary>
	/// 図形の種類 
	///	</summary>
	public enum ShapeType : int
	{
		/// <summary>
		/// 円 
		/// </summary>
		CircleShape = asd.swig.ShapeType.CircleShape,
		/// <summary>
		/// 弧 
		/// </summary>
		ArcShape = asd.swig.ShapeType.ArcShape,
		/// <summary>
		/// 線分 
		/// </summary>
		LineShape = asd.swig.ShapeType.LineShape,
		/// <summary>
		/// 矩形 
		/// </summary>
		RectangleShape = asd.swig.ShapeType.RectangleShape,
		/// <summary>
		/// 三角形 
		/// </summary>
		TriangleShape = asd.swig.ShapeType.TriangleShape,
		/// <summary>
		/// 多角形 
		/// </summary>
		PolygonShape = asd.swig.ShapeType.PolygonShape,
	}

	/// <summary>
	/// 
	///	</summary>
	public enum ChildMode : int
	{
		/// <summary>
		/// 
		/// </summary>
		Position = asd.swig.ChildMode.Position,
		/// <summary>
		/// 
		/// </summary>
		All = asd.swig.ChildMode.All,
		/// <summary>
		/// 
		/// </summary>
		Nothing = asd.swig.ChildMode.Nothing,
	}

	/// <summary>
	/// エフェクトの情報が記録されているクラス 
	/// </summary>
	public partial class Effect
	{
		internal asd.swig.Effect CoreInstance { get; set; }


	}


	/// <summary>
	/// 
	/// </summary>
	public partial class File
	{
		internal asd.swig.File CoreInstance { get; set; }


		/// <summary>
		/// 
		/// </summary>
		/// <param name="path"></param>
		public void AddRootDirectory(string path)
		{
			CoreInstance.AddRootDirectory(path);
		}

		/// <summary>
		/// 
		/// </summary>
		/// <param name="path"></param>
		/// <param name="password"></param>
		public void AddRootPackageWithPassword(string path, string password)
		{
			CoreInstance.AddRootPackageWithPassword(path, password);
		}

		/// <summary>
		/// 
		/// </summary>
		/// <param name="path"></param>
		public void AddRootPackage(string path)
		{
			CoreInstance.AddRootPackage(path);
		}

		/// <summary>
		/// 
		/// </summary>
		public void ClearRootDirectories()
		{
			CoreInstance.ClearRootDirectories();
		}

		/// <summary>
		/// 
		/// </summary>
		/// <param name="path"></param>
		/// <returns></returns>
		public bool Exists(string path)
		{
			return CoreInstance.Exists(path);
		}

	}


	/// <summary>
	/// フォントの情報が記録されているクラス 
	/// </summary>
	public partial class Font
	{
		internal asd.swig.Font CoreInstance { get; set; }


		/// <summary>
		/// 描画テキストと描画方向を与えると、その文字の描画領域を返す。 
		/// </summary>
		/// <param name="text">描画テキスト </param>
		/// <param name="writingDirection">描画方向 </param>
		/// <returns>文字の描画領域 </returns>
		public asd.Vector2DI CalcTextureSize(string text, WritingDirection writingDirection)
		{
			return CoreInstance.CalcTextureSize(text, (asd.swig.WritingDirection)writingDirection);
		}

	}


	/// <summary>
	/// 複数の画像が格納されているクラス 
	/// </summary>
	public partial class ImagePackage
	{
		internal asd.swig.ImagePackage CoreInstance { get; set; }

		/// <summary>
		/// 格納されている画像の枚数を取得する。
		/// </summary>
		public int ImageCount
		{
			get { return CoreInstance.GetImageCount(); }
		}


		/// <summary>
		/// 格納されている画像の名称を取得する。 
		/// </summary>
		/// <param name="index">インデックス </param>
		/// <returns>名称 </returns>
		public string GetImageName(int index)
		{
			return CoreInstance.GetImageName(index);
		}

		/// <summary>
		/// 格納されている画像が配置される領域を取得する。 
		/// </summary>
		/// <param name="index">インデックス </param>
		/// <returns>領域 </returns>
		public asd.RectI GetImageArea(int index)
		{
			return CoreInstance.GetImageArea(index);
		}

	}


	/// <summary>
	/// 指定したコンポーネントをこのインスタンスに追加する。 
	/// </summary>
	public partial class Joystick
	{
		internal asd.swig.Joystick CoreInstance { get; set; }

		/// <summary>
		/// 
		/// </summary>
		public string JoystickName
		{
			get { return CoreInstance.GetJoystickName(); }
		}

		/// <summary>
		/// 
		/// </summary>
		public int ButtonsCount
		{
			get { return CoreInstance.GetButtonsCount(); }
		}

		/// <summary>
		/// 
		/// </summary>
		public int AxesCount
		{
			get { return CoreInstance.GetAxesCount(); }
		}


		/// <summary>
		/// 指定したボタンの押し状態を返す 
		/// </summary>
		/// <param name="at">何番目のボタンの押し状態を取得するか </param>
		/// <returns>押し状態 </returns>
		public JoystickButtonState GetButtonState(int at)
		{
			return (asd.JoystickButtonState)CoreInstance.GetButtonState(at);
		}

		/// <summary>
		/// 指定した軸の倒し具合を返す 
		/// </summary>
		/// <param name="at">何番目の軸配列の倒し具合を取得するか </param>
		/// <returns>倒し具合 </returns>
		public float GetAxisState(int at)
		{
			return CoreInstance.GetAxisState(at);
		}

	}


	/// <summary>
	/// 
	/// </summary>
	public partial class JoystickContainer
	{
		internal asd.swig.JoystickContainer CoreInstance { get; set; }


		/// <summary>
		/// 引数に指定した番号のジョイスティックが接続されているかを取得する。 
		/// </summary>
		/// <param name="at">何番目のジョイスティックの接続を確認するか </param>
		/// <returns>接続されているか否か </returns>
		public bool GetIsPresentAt(int at)
		{
			return CoreInstance.GetIsPresentAt(at);
		}

		/// <summary>
		/// 全てのジョイスティックの接続状態を更新する。 
		/// </summary>
		public void RefreshAllJoysticks()
		{
			CoreInstance.RefreshAllJoysticks();
		}

	}


	/// <summary>
	/// キーボードからの入力を取得するクラス 
	/// </summary>
	public partial class Keyboard
	{
		internal asd.swig.Keyboard CoreInstance { get; set; }


		/// <summary>
		/// 特定のキーの押し状態をKeyState列挙型で返す 
		/// </summary>
		/// <param name="key"></param>
		/// <returns>押し状態 </returns>
		public KeyState GetKeyState(Keys key)
		{
			return (asd.KeyState)CoreInstance.GetKeyState((asd.swig.Keys)key);
		}

	}


	/// <summary>
	/// 
	/// </summary>
	public partial class Log
	{
		internal asd.swig.Log CoreInstance { get; set; }

		/// <summary>
		/// ログの出力が可能であるかどうかを表す真偽値を取得する。
		/// </summary>
		public bool IsValid
		{
			get { return CoreInstance.GetIsValid(); }
		}

		/// <summary>
		/// ログの出力レベルを設定する。
		/// </summary>
		public LogLevel OutputLevel
		{
			set { CoreInstance.SetOutputLevel((asd.swig.LogLevel)value); }
		}


		/// <summary>
		/// ログ ファイルへ文字列を書き込む。 
		/// </summary>
		/// <param name="text">[in] 書き込む文字列 </param>
		/// <param name="level">[in] ログの出力レベル </param>
		public void Write(string text, LogLevel level)
		{
			CoreInstance.Write(text, (asd.swig.LogLevel)level);
		}

		/// <summary>
		/// ログ ファイルへ文字列を書き込む。 
		/// </summary>
		/// <param name="text">[in] 書き込む文字列 </param>
		public void Write(string text)
		{
			CoreInstance.Write(text);
		}

		/// <summary>
		/// ログ ファイルへ文字列を書き込み、改行する。 
		/// </summary>
		/// <param name="text">[in] 書き込む文字列 </param>
		/// <param name="level">[in] ログの出力レベル </param>
		public void WriteLine(string text, LogLevel level)
		{
			CoreInstance.WriteLine(text, (asd.swig.LogLevel)level);
		}

		/// <summary>
		/// ログ ファイルへ文字列を書き込み、改行する。 
		/// </summary>
		/// <param name="text">[in] 書き込む文字列 </param>
		public void WriteLine(string text)
		{
			CoreInstance.WriteLine(text);
		}

		/// <summary>
		/// ログ ファイルへ強調された文字列を書き込む。 
		/// </summary>
		/// <param name="text">[in] 書き込む文字列 </param>
		/// <param name="level">[in] ログの出力レベル </param>
		public void WriteStrongly(string text, LogLevel level)
		{
			CoreInstance.WriteStrongly(text, (asd.swig.LogLevel)level);
		}

		/// <summary>
		/// ログ ファイルへ強調された文字列を書き込む。 
		/// </summary>
		/// <param name="text">[in] 書き込む文字列 </param>
		public void WriteStrongly(string text)
		{
			CoreInstance.WriteStrongly(text);
		}

		/// <summary>
		/// ログ ファイルへ強調された文字列を書き込み、改行する。 
		/// </summary>
		/// <param name="text">[in] 書き込む文字列 </param>
		/// <param name="level">[in] ログの出力レベル </param>
		public void WriteLineStrongly(string text, LogLevel level)
		{
			CoreInstance.WriteLineStrongly(text, (asd.swig.LogLevel)level);
		}

		/// <summary>
		/// ログ ファイルへ強調された文字列を書き込み、改行する。 
		/// </summary>
		/// <param name="text">[in] 書き込む文字列 </param>
		public void WriteLineStrongly(string text)
		{
			CoreInstance.WriteLineStrongly(text);
		}

		/// <summary>
		/// ログ ファイルへ見出しとして文字列を書き込む。 
		/// </summary>
		/// <param name="text">[in] 書き込む文字列 </param>
		/// <param name="level">[in] ログの出力レベル </param>
		public void WriteHeading(string text, LogLevel level)
		{
			CoreInstance.WriteHeading(text, (asd.swig.LogLevel)level);
		}

		/// <summary>
		/// ログ ファイルへ見出しとして文字列を書き込む。 
		/// </summary>
		/// <param name="text">[in] 書き込む文字列 </param>
		public void WriteHeading(string text)
		{
			CoreInstance.WriteHeading(text);
		}

		/// <summary>
		/// ログ ファイルへ水平線を書き込む。 
		/// </summary>
		/// <param name="level">[in] ログの出力レベル </param>
		public void WriteHorizontalRule(LogLevel level)
		{
			CoreInstance.WriteHorizontalRule((asd.swig.LogLevel)level);
		}

		/// <summary>
		/// ログ ファイルへ水平線を書き込む。 
		/// </summary>
		public void WriteHorizontalRule()
		{
			CoreInstance.WriteHorizontalRule();
		}

		/// <summary>
		/// ログ ファイルへ表形式( 
		/// </summary>
		/// <param name="level">[in] ログの出力レベル </param>
		public void BeginTable(LogLevel level)
		{
			CoreInstance.BeginTable((asd.swig.LogLevel)level);
		}

		/// <summary>
		/// ログ ファイルへ表形式( 
		/// </summary>
		public void BeginTable()
		{
			CoreInstance.BeginTable();
		}

		/// <summary>
		/// ログ ファイルへの表形式( 
		/// </summary>
		/// <param name="level">[in] ログの出力レベル </param>
		public void EndTable(LogLevel level)
		{
			CoreInstance.EndTable((asd.swig.LogLevel)level);
		}

		/// <summary>
		/// ログ ファイルへの表形式( 
		/// </summary>
		public void EndTable()
		{
			CoreInstance.EndTable();
		}

		/// <summary>
		/// 表形式での出力において、新しい行に移動する。 
		/// </summary>
		/// <param name="level">[in] ログの出力レベル </param>
		public void ChangeRow(LogLevel level)
		{
			CoreInstance.ChangeRow((asd.swig.LogLevel)level);
		}

		/// <summary>
		/// 表形式での出力において、新しい行に移動する。 
		/// </summary>
		public void ChangeRow()
		{
			CoreInstance.ChangeRow();
		}

		/// <summary>
		/// 表形式での出力において、新しい列に移動する。 
		/// </summary>
		/// <param name="level">[in] ログの出力レベル </param>
		public void ChangeColumn(LogLevel level)
		{
			CoreInstance.ChangeColumn((asd.swig.LogLevel)level);
		}

		/// <summary>
		/// 表形式での出力において、新しい列に移動する。 
		/// </summary>
		public void ChangeColumn()
		{
			CoreInstance.ChangeColumn();
		}

	}


	/// <summary>
	/// 大量描画が可能な3Dモデルクラス 
	/// </summary>
	public partial class MassModel
	{
		internal asd.swig.MassModel CoreInstance { get; set; }

		/// <summary>
		/// モデルが持つアニメーションの個数を取得する。
		/// </summary>
		public int AnimationCount
		{
			get { return CoreInstance.GetAnimationCount(); }
		}


		/// <summary>
		/// モデルが持つアニメーションの名称を取得する。 
		/// </summary>
		/// <param name="index">アニメーションのインデックス </param>
		/// <returns>アニメーションの名称 </returns>
		public string GetAnimationName(int index)
		{
			return CoreInstance.GetAnimationName(index);
		}

		/// <summary>
		/// モデルが持つアニメーションの長さ(60フレーム単位)を取得する。 
		/// </summary>
		/// <param name="name">アニメーション名 </param>
		/// <returns>アニメーションの長さ </returns>
		public float GetAnimationLength(string name)
		{
			return CoreInstance.GetAnimationLength(name);
		}

		/// <summary>
		/// アニメーションがループするかを取得する。 
		/// </summary>
		/// <param name="name">アニメーション名 </param>
		/// <returns>ループするか? </returns>
		public bool GetIsAnimationLoopingMode(string name)
		{
			return CoreInstance.GetIsAnimationLoopingMode(name);
		}

		/// <summary>
		/// アニメーションがループするかを設定する。 
		/// </summary>
		/// <param name="name">アニメーション名 </param>
		/// <param name="isLoopingMode"></param>
		public void SetIsAnimationLoopingMode(string name, bool isLoopingMode)
		{
			CoreInstance.SetIsAnimationLoopingMode(name, isLoopingMode);
		}

	}


	/// <summary>
	/// 
	/// </summary>
	public partial class Material2D
	{
		internal asd.swig.Material2D CoreInstance { get; set; }


		/// <summary>
		/// 
		/// </summary>
		/// <param name="name"></param>
		/// <returns></returns>
		public float GetFloat(string name)
		{
			return CoreInstance.GetFloat(name);
		}

		/// <summary>
		/// 
		/// </summary>
		/// <param name="name"></param>
		/// <param name="value"></param>
		public void SetFloat(string name, float value)
		{
			CoreInstance.SetFloat(name, value);
		}

		/// <summary>
		/// 
		/// </summary>
		/// <param name="name"></param>
		/// <returns></returns>
		public asd.Vector2DF GetVector2DF(string name)
		{
			return CoreInstance.GetVector2DF(name);
		}

		/// <summary>
		/// 
		/// </summary>
		/// <param name="name"></param>
		/// <param name="value"></param>
		public void SetVector2DF(string name, asd.Vector2DF value)
		{
			CoreInstance.SetVector2DF(name, value);
		}

		/// <summary>
		/// 
		/// </summary>
		/// <param name="name"></param>
		/// <returns></returns>
		public asd.Vector3DF GetVector3DF(string name)
		{
			return CoreInstance.GetVector3DF(name);
		}

		/// <summary>
		/// 
		/// </summary>
		/// <param name="name"></param>
		/// <param name="value"></param>
		public void SetVector3DF(string name, asd.Vector3DF value)
		{
			CoreInstance.SetVector3DF(name, value);
		}

		/// <summary>
		/// 
		/// </summary>
		/// <param name="name"></param>
		/// <returns></returns>
		public asd.Vector4DF GetVector4DF(string name)
		{
			return CoreInstance.GetVector4DF(name);
		}

		/// <summary>
		/// 
		/// </summary>
		/// <param name="name"></param>
		/// <param name="value"></param>
		public void SetVector4DF(string name, asd.Vector4DF value)
		{
			CoreInstance.SetVector4DF(name, value);
		}

		/// <summary>
		/// 
		/// </summary>
		/// <param name="name"></param>
		/// <param name="value"></param>
		public void SetTexture2D(string name, Texture2D value)
		{
			var valueCore = value != null ? value.CoreInstance : null;
			CoreInstance.SetTexture2D(name, valueCore);
		}

		/// <summary>
		/// 
		/// </summary>
		/// <param name="name"></param>
		/// <returns></returns>
		public TextureFilterType GetTextureFilterType(string name)
		{
			return (asd.TextureFilterType)CoreInstance.GetTextureFilterType(name);
		}

		/// <summary>
		/// 
		/// </summary>
		/// <param name="name"></param>
		/// <param name="filter"></param>
		public void SetTextureFilterType(string name, TextureFilterType filter)
		{
			CoreInstance.SetTextureFilterType(name, (asd.swig.TextureFilterType)filter);
		}

		/// <summary>
		/// 
		/// </summary>
		/// <param name="name"></param>
		/// <returns></returns>
		public TextureWrapType GetTextureWrapType(string name)
		{
			return (asd.TextureWrapType)CoreInstance.GetTextureWrapType(name);
		}

		/// <summary>
		/// 
		/// </summary>
		/// <param name="name"></param>
		/// <param name="wrap"></param>
		public void SetTextureWrapType(string name, TextureWrapType wrap)
		{
			CoreInstance.SetTextureWrapType(name, (asd.swig.TextureWrapType)wrap);
		}

	}


	/// <summary>
	/// 
	/// </summary>
	public partial class Material3D
	{
		internal asd.swig.Material3D CoreInstance { get; set; }


		/// <summary>
		/// 
		/// </summary>
		/// <param name="name"></param>
		/// <returns></returns>
		public float GetFloat(string name)
		{
			return CoreInstance.GetFloat(name);
		}

		/// <summary>
		/// 
		/// </summary>
		/// <param name="name"></param>
		/// <param name="value"></param>
		public void SetFloat(string name, float value)
		{
			CoreInstance.SetFloat(name, value);
		}

		/// <summary>
		/// 
		/// </summary>
		/// <param name="name"></param>
		/// <returns></returns>
		public asd.Vector2DF GetVector2DF(string name)
		{
			return CoreInstance.GetVector2DF(name);
		}

		/// <summary>
		/// 
		/// </summary>
		/// <param name="name"></param>
		/// <param name="value"></param>
		public void SetVector2DF(string name, asd.Vector2DF value)
		{
			CoreInstance.SetVector2DF(name, value);
		}

		/// <summary>
		/// 
		/// </summary>
		/// <param name="name"></param>
		/// <returns></returns>
		public asd.Vector3DF GetVector3DF(string name)
		{
			return CoreInstance.GetVector3DF(name);
		}

		/// <summary>
		/// 
		/// </summary>
		/// <param name="name"></param>
		/// <param name="value"></param>
		public void SetVector3DF(string name, asd.Vector3DF value)
		{
			CoreInstance.SetVector3DF(name, value);
		}

		/// <summary>
		/// 
		/// </summary>
		/// <param name="name"></param>
		/// <returns></returns>
		public asd.Vector4DF GetVector4DF(string name)
		{
			return CoreInstance.GetVector4DF(name);
		}

		/// <summary>
		/// 
		/// </summary>
		/// <param name="name"></param>
		/// <param name="value"></param>
		public void SetVector4DF(string name, asd.Vector4DF value)
		{
			CoreInstance.SetVector4DF(name, value);
		}

		/// <summary>
		/// 
		/// </summary>
		/// <param name="name"></param>
		/// <param name="value"></param>
		public void SetTexture2D(string name, Texture2D value)
		{
			var valueCore = value != null ? value.CoreInstance : null;
			CoreInstance.SetTexture2D(name, valueCore);
		}

		/// <summary>
		/// 
		/// </summary>
		/// <param name="name"></param>
		/// <returns></returns>
		public TextureFilterType GetTextureFilterType(string name)
		{
			return (asd.TextureFilterType)CoreInstance.GetTextureFilterType(name);
		}

		/// <summary>
		/// 
		/// </summary>
		/// <param name="name"></param>
		/// <param name="filter"></param>
		public void SetTextureFilterType(string name, TextureFilterType filter)
		{
			CoreInstance.SetTextureFilterType(name, (asd.swig.TextureFilterType)filter);
		}

		/// <summary>
		/// 
		/// </summary>
		/// <param name="name"></param>
		/// <returns></returns>
		public TextureWrapType GetTextureWrapType(string name)
		{
			return (asd.TextureWrapType)CoreInstance.GetTextureWrapType(name);
		}

		/// <summary>
		/// 
		/// </summary>
		/// <param name="name"></param>
		/// <param name="wrap"></param>
		public void SetTextureWrapType(string name, TextureWrapType wrap)
		{
			CoreInstance.SetTextureWrapType(name, (asd.swig.TextureWrapType)wrap);
		}

	}


	/// <summary>
	/// 3Dメッシュのクラス 
	/// </summary>
	public partial class Mesh
	{
		internal asd.swig.Mesh CoreInstance { get; set; }


		/// <summary>
		/// 頂点を追加する。 
		/// </summary>
		/// <param name="position">座標 </param>
		/// <param name="normal">法線 </param>
		/// <param name="binormal">従法線 </param>
		/// <param name="uv1">UV1 </param>
		/// <param name="uv2">UV2 </param>
		/// <param name="color">頂点色 </param>
		/// <param name="boneWeights">ボーンのウエイト </param>
		/// <param name="boneIndexes">ボーンのインデックス </param>
		public void AddVertex(asd.Vector3DF position, asd.Vector3DF normal, asd.Vector3DF binormal, asd.Vector2DF uv1, asd.Vector2DF uv2, asd.Color color, int boneWeights, int boneIndexes)
		{
			CoreInstance.AddVertex(ref position, ref normal, ref binormal, ref uv1, ref uv2, ref color, boneWeights, boneIndexes);
		}

		/// <summary>
		/// 面を追加する。 
		/// </summary>
		/// <param name="index1">頂点インデックス1 </param>
		/// <param name="index2">頂点インデックス2 </param>
		/// <param name="index3">頂点インデックス3 </param>
		/// <param name="materialIndex">材質インデックス </param>
		public void AddFace(int index1, int index2, int index3, int materialIndex)
		{
			CoreInstance.AddFace(index1, index2, index3, materialIndex);
		}

		/// <summary>
		/// ボーンとの接続設定を追加する。 
		/// </summary>
		/// <param name="targetIndex">対象ボーンインデックス </param>
		/// <param name="boneToMesh">ボーンの行列をメッシュの行列に変換する行列 </param>
		public void AddBoneConnector(int targetIndex, asd.Matrix44 boneToMesh)
		{
			CoreInstance.AddBoneConnector(targetIndex, ref boneToMesh);
		}

		/// <summary>
		/// 材質を追加する。 
		/// </summary>
		/// <returns>材質のインデックス </returns>
		public int AddMaterial()
		{
			return CoreInstance.AddMaterial();
		}

		/// <summary>
		/// 設定した値をGPUに送信する。 
		/// </summary>
		public void SendToGPUMemory()
		{
			CoreInstance.SendToGPUMemory();
		}

		/// <summary>
		/// 内部シェーダーを使用する場合のカラーテクスチャを設定する。 
		/// </summary>
		/// <param name="materialIndex">材質のインデックス </param>
		/// <param name="texture"></param>
		public void SetColorTexture(int materialIndex, Texture2D texture)
		{
			var textureCore = texture != null ? texture.CoreInstance : null;
			CoreInstance.SetColorTexture(materialIndex, textureCore);
		}

		/// <summary>
		/// 内部シェーダーを使用する場合の法線テクスチャを設定する。 
		/// </summary>
		/// <param name="materialIndex">材質のインデックス </param>
		/// <param name="texture"></param>
		public void SetNormalTexture(int materialIndex, Texture2D texture)
		{
			var textureCore = texture != null ? texture.CoreInstance : null;
			CoreInstance.SetNormalTexture(materialIndex, textureCore);
		}

		/// <summary>
		/// 内部シェーダーを使用する場合の金属度テクスチャを設定する。 
		/// </summary>
		/// <param name="materialIndex">材質のインデックス </param>
		/// <param name="texture"></param>
		public void SetMetalnessTexture(int materialIndex, Texture2D texture)
		{
			var textureCore = texture != null ? texture.CoreInstance : null;
			CoreInstance.SetMetalnessTexture(materialIndex, textureCore);
		}

		/// <summary>
		/// 内部シェーダーを使用する場合の面平滑度テクスチャを設定する。 
		/// </summary>
		/// <param name="materialIndex">材質のインデックス </param>
		/// <param name="texture"></param>
		public void SetSmoothnessTexture(int materialIndex, Texture2D texture)
		{
			var textureCore = texture != null ? texture.CoreInstance : null;
			CoreInstance.SetSmoothnessTexture(materialIndex, textureCore);
		}

	}


	/// <summary>
	/// 3Dモデルクラス 
	/// </summary>
	public partial class Model
	{
		internal asd.swig.Model CoreInstance { get; set; }

		/// <summary>
		/// モデルが持つメッシュの個数を取得する。
		/// </summary>
		public int MeshCount
		{
			get { return CoreInstance.GetMeshCount(); }
		}

		/// <summary>
		/// モデルが持つアニメーションクリップの個数を取得する。
		/// </summary>
		public int AnimationClipCount
		{
			get { return CoreInstance.GetAnimationClipCount(); }
		}


		/// <summary>
		/// モデルが持つアニメーションクリップの名称を取得する。 
		/// </summary>
		/// <param name="index">アニメーションクリップのインデックス </param>
		/// <returns>アニメーションクリップの名称 </returns>
		public string GetAnimationClipName(int index)
		{
			return CoreInstance.GetAnimationClipName(index);
		}

	}


	/// <summary>
	/// 
	/// </summary>
	public partial class Mouse
	{
		internal asd.swig.Mouse CoreInstance { get; set; }

		/// <summary>
		/// 
		/// </summary>
		public asd.Vector2DF Position
		{
			get { return CoreInstance.GetPosition(); }
		}


	}


	/// <summary>
	/// プログラムの実行状況(計算時間や、使っているプロセッサ)を記録するクラス。 
	/// </summary>
	public partial class Profiler
	{
		internal asd.swig.Profiler CoreInstance { get; set; }


		/// <summary>
		/// 計算の開始時間と、使用するプロセッサ番号を記録する。 
		/// </summary>
		/// <param name="id">プロファイリングを識別するID。Start関数は、IDの一致するEnd関数と対応する。 </param>
		public void Start(int id)
		{
			CoreInstance.Start(id);
		}

		/// <summary>
		/// 計算の終了時間を記録し、プロファイリング結果を蓄積する。 
		/// </summary>
		/// <param name="id">プロファイリングを識別するID。End関数は、IDの一致するStart関数と対応する。 </param>
		public void End(int id)
		{
			CoreInstance.End(id);
		}

	}


	/// <summary>
	/// シェーダー(2D) 
	/// </summary>
	public partial class Shader2D
	{
		internal asd.swig.Shader2D CoreInstance { get; set; }


	}


	/// <summary>
	/// シェーダー(3D) 
	/// </summary>
	public partial class Shader3D
	{
		internal asd.swig.Shader3D CoreInstance { get; set; }


	}


	/// <summary>
	/// 音を管理するクラス 
	/// </summary>
	public partial class Sound
	{
		internal asd.swig.Sound CoreInstance { get; set; }


		/// <summary>
		/// 音を再生する。 
		/// </summary>
		/// <param name="soundSource">音源 </param>
		/// <returns>ID </returns>
		public int Play(SoundSource soundSource)
		{
			var soundSourceCore = soundSource != null ? soundSource.CoreInstance : null;
			return CoreInstance.Play(soundSourceCore);
		}

		/// <summary>
		/// 音が再生中か、取得する。 
		/// </summary>
		/// <param name="id">ID </param>
		/// <returns>再生中か? </returns>
		public bool GetIsPlaying(int id)
		{
			return CoreInstance.GetIsPlaying(id);
		}

		/// <summary>
		/// 全ての再生中の音を停止する。 
		/// </summary>
		public void StopAll()
		{
			CoreInstance.StopAll();
		}

		/// <summary>
		/// 指定した音を停止する。 
		/// </summary>
		/// <param name="id">ID </param>
		public void Stop(int id)
		{
			CoreInstance.Stop(id);
		}

		/// <summary>
		/// 指定した音を一時停止する。 
		/// </summary>
		/// <param name="id">ID </param>
		public void Pause(int id)
		{
			CoreInstance.Pause(id);
		}

		/// <summary>
		/// 指定した一時停止中の音の一時停止を解除する。 
		/// </summary>
		/// <param name="id">ID </param>
		public void Resume(int id)
		{
			CoreInstance.Resume(id);
		}

		/// <summary>
		/// 指定した音の音量を設定する。 
		/// </summary>
		/// <param name="id">ID </param>
		/// <param name="volume">音量(0.0～1.0) </param>
		public void SetVolume(int id, float volume)
		{
			CoreInstance.SetVolume(id, volume);
		}

		/// <summary>
		/// 指定した音をフェードインさせる。 
		/// </summary>
		/// <param name="id">ID </param>
		/// <param name="second">フェードインに使用する時間(秒) </param>
		public void FadeIn(int id, float second)
		{
			CoreInstance.FadeIn(id, second);
		}

		/// <summary>
		/// 指定した音をフェードアウトさせる。 
		/// </summary>
		/// <param name="id">ID </param>
		/// <param name="second">フェードアウトに使用する時間(秒) </param>
		public void FadeOut(int id, float second)
		{
			CoreInstance.FadeOut(id, second);
		}

	}


	/// <summary>
	/// 音源のクラス 
	/// </summary>
	public partial class SoundSource
	{
		internal asd.swig.SoundSource CoreInstance { get; set; }

		/// <summary>
		/// ループポイントの開始地点(秒)を取得または設定する。
		/// </summary>
		public float LoopStartingPoint
		{
			get { return CoreInstance.GetLoopStartingPoint(); }
			set { CoreInstance.SetLoopStartingPoint(value); }
		}

		/// <summary>
		/// ループポイントの終了地点(秒)を取得または設定する。
		/// </summary>
		public float LoopEndPoint
		{
			get { return CoreInstance.GetLoopEndPoint(); }
			set { CoreInstance.SetLoopEndPoint(value); }
		}

		/// <summary>
		/// ループするかを取得または設定する。
		/// </summary>
		public bool IsLoopingMode
		{
			get { return CoreInstance.GetIsLoopingMode(); }
			set { CoreInstance.SetIsLoopingMode(value); }
		}

		/// <summary>
		/// 音の長さを取得する。
		/// </summary>
		public float Length
		{
			get { return CoreInstance.GetLength(); }
		}


	}


	/// <summary>
	/// 
	/// </summary>
	public partial class StaticFile
	{
		internal asd.swig.StaticFile CoreInstance { get; set; }

		/// <summary>
		/// 
		/// </summary>
		public string FullPath
		{
			get { return CoreInstance.GetFullPath(); }
		}

		/// <summary>
		/// 
		/// </summary>
		public System.IntPtr Data
		{
			get { return CoreInstance.GetData(); }
		}

		/// <summary>
		/// 
		/// </summary>
		public int Size
		{
			get { return CoreInstance.GetSize(); }
		}


	}


	/// <summary>
	/// 
	/// </summary>
	public partial class StreamFile
	{
		internal asd.swig.StreamFile CoreInstance { get; set; }

		/// <summary>
		/// 
		/// </summary>
		public int Size
		{
			get { return CoreInstance.GetSize(); }
		}

		/// <summary>
		/// 
		/// </summary>
		public int CurrentPosition
		{
			get { return CoreInstance.GetCurrentPosition(); }
		}


	}


	/// <summary>
	/// 地形のクラス 
	/// </summary>
	public partial class Terrain3D
	{
		internal asd.swig.Terrain3D CoreInstance { get; set; }


		/// <summary>
		/// 新規に地形を作成する。 
		/// </summary>
		/// <param name="gridSize">グリッド1つ当たりの大きさ </param>
		/// <param name="gridWidthCount">横方向のグリッド数 </param>
		/// <param name="gridHeightCount">縦方向のグリッド数 </param>
		public void New(float gridSize, int gridWidthCount, int gridHeightCount)
		{
			CoreInstance.New(gridSize, gridWidthCount, gridHeightCount);
		}

		/// <summary>
		/// 素材を追加する。 
		/// </summary>
		/// <param name="name">素材名 </param>
		/// <param name="size">素材のテクスチャ1枚あたりの大きさ </param>
		/// <param name="color">色テクスチャのパス </param>
		/// <param name="normal">法線テクスチャのパス </param>
		/// <param name="metalness">スペキュラテクスチャのパス </param>
		public void AddSurface(string name, float size, string color, string normal, string metalness)
		{
			CoreInstance.AddSurface(name, size, color, normal, metalness);
		}

		/// <summary>
		/// 素材インデックスを取得する。 
		/// </summary>
		/// <param name="name">素材名 </param>
		/// <returns>素材インデックス </returns>
		public int GetSurfaceIndex(string name)
		{
			return CoreInstance.GetSurfaceIndex(name);
		}

		/// <summary>
		/// 素材を円形に割り当てる。 
		/// </summary>
		/// <param name="surfaceIndex">素材インデックス </param>
		/// <param name="x">円形の中心座標 </param>
		/// <param name="y">円形の中心座標 </param>
		/// <param name="radius">円形の半径 </param>
		/// <param name="value">割り当てる値(-255～255) </param>
		/// <param name="fallout">周囲のぼかし(0～1) </param>
		public void AssignSurfaceWithCircle(int surfaceIndex, float x, float y, float radius, float value, float fallout)
		{
			CoreInstance.AssignSurfaceWithCircle(surfaceIndex, x, y, radius, value, fallout);
		}

		/// <summary>
		/// 円形に地形を上下させる。 
		/// </summary>
		/// <param name="x">円形の中心座標 </param>
		/// <param name="y">円形の中心座標 </param>
		/// <param name="radius">円形の半径 </param>
		/// <param name="value">値 </param>
		/// <param name="fallout">周囲のぼかし(0～1) </param>
		public void RaiseWithCircle(float x, float y, float radius, float value, float fallout)
		{
			CoreInstance.RaiseWithCircle(x, y, radius, value, fallout);
		}

		/// <summary>
		/// 円形に崖の生成を伴う地形の上下をさせる。 
		/// </summary>
		/// <param name="x">円形の中心座標 </param>
		/// <param name="y">円形の中心座標 </param>
		/// <param name="radius">円形の半径 </param>
		/// <param name="value">値 </param>
		public void ChangeCliffesWithCircle(float x, float y, float radius, int value)
		{
			CoreInstance.ChangeCliffesWithCircle(x, y, radius, value);
		}

		/// <summary>
		/// 光線を飛ばし、衝突した位置を取得する。 
		/// </summary>
		/// <param name="from">光線を飛ばす元の位置 </param>
		/// <param name="to">光線を飛ばす先の位置 </param>
		/// <returns>光線が地形に衝突した位置。衝突しない場合、NaNを返す。 </returns>
		public asd.Vector3DF CastRay(asd.Vector3DF from, asd.Vector3DF to)
		{
			return CoreInstance.CastRay(ref from, ref to);
		}

	}


	/// <summary>
	/// 
	/// </summary>
	public partial class Texture2D
	{
		internal asd.swig.Texture2D CoreInstance { get; set; }

		/// <summary>
		/// テクスチャのサイズを取得する。
		/// </summary>
		public asd.Vector2DI Size
		{
			get { return CoreInstance.GetSize(); }
		}

		/// <summary>
		/// テクスチャのフォーマットを取得する。
		/// </summary>
		public TextureFormat Format
		{
			get { return (asd.TextureFormat)CoreInstance.GetFormat(); }
		}

		/// <summary>
		/// テクスチャのクラスの種類を取得する。
		/// </summary>
		public TextureClassType Type
		{
			get { return (asd.TextureClassType)CoreInstance.GetType(); }
		}


		/// <summary>
		/// テクスチャをファイルに保存する。 
		/// </summary>
		/// <param name="path">出力先 </param>
		/// <returns>成否 </returns>
		public bool Save(string path)
		{
			return CoreInstance.Save(path);
		}

		/// <summary>
		/// テクスチャをアンロックする。 
		/// </summary>
		public void Unlock()
		{
			CoreInstance.Unlock();
		}

	}


}
