/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace ace.swig {

public enum AlphaBlendMode {
  Opacity = 0,
  Blend = 1,
  Add = 2,
  Sub = 3,
  Mul = 4,
  AddAll = 5
}

}
