/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace ace.swig {

public enum LogLevel {
  Error = 1 << 1,
  Critical = 1 << 2,
  Warning = 1 << 3,
  Information = 1 << 4,
  All = 2147483647
}

}
